lets/config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :users do 
    member do
      post   '/admin',   to: 'admins#create'
      delete '/admin',   to: 'admins#destroy'
    end
    resources :purchases, only: [:index]
    resources :events, only: [:index]
  end
  resources :producers do
    resources :prod_owners, only: [:create] 
    resources :events, only: [:index, :new, :create]
  end
  resources :prod_owners, only: [:update, :destroy]
  resources :events, only: [:update, :destroy, :show, :index, :edit] do
    resources :combos, only: [:new, :create]
  end
  resources :combos, only: [:show, :update, :destroy] do
    resources :offers, only: [:create]
    resources :purchases, only: [:create]
  end
  resources :offers, only: [:update, :destroy]
  resources :purchases, only: [:destroy, :show]
  resources :products

	root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

lets/app/models/combo.rb
class Combo < ApplicationRecord
	require 'exceptions.rb'

	belongs_to :event
	has_many :offers, dependent: :destroy

	validates :name,		 			presence: true, length:{maximum: 50, minimum: 5}
	validates :description,	 	presence: true, length:{maximum: 250, minimum: 10}
	validates :min_age,		 		presence: true, :inclusion => 14..100, numericality: { only_integer: true }
	validates :max_age,		 		presence: true, :inclusion => 14..100, numericality: { only_integer: true }
	validates :gender,		 		presence: true, :inclusion => 0..2, numericality: { only_integer: true }
	validates :stock,		 			presence: true, :inclusion => 1..1000000, numericality: { only_integer: true }
  validates :buyable_from, 	presence: true
  validates :buyable_until, presence: true
  #E.G: validates_inclusion_of :birth_date, in: (100.years.ago)..(5.years.ago)

  validates_format_of :name, with: /\A[A-Za-z0-9\&\@\#\.\$]+([\!\?]{0,4}(\ |\,\ |\:\ )?[A-Za-z0-9\&\@\#\.\$]+)*[\!\?]{0,4}\z/i

  def price
  	total = 0
  	self.offers.each do |offer|
  		total += offer.price
  	end
  	return total
  end

  def buyable user
  	check user
  	@errors
  end

  def buying_errors
  	@errors
  end

  def buy user
  	ActiveRecord::Base.transaction do
	  	check! user
	  	set_exception "Requires higher level" if not check_levels user
			self.offers.each do |offer|
				offer.buy user
			end
			self.lock!
			if self.stock > 0
				self.stock -= 1
				self.save!
			else
				set_exception "This item is out of stock"
			end
		end
		true
	rescue Exceptions::ComboRestrictionsException => error
		#Debugging purposes only
		#puts "!!!--- #{error.message} ---!!!"
		false
  end

  def check_levels user
  	max_required = nil
  	admission = Admission.get_or_new(user, self.event)
  	max_provided = admission.access_level
  	self.offers.each do |offer|
  		provided_level = offer.provided_level
  		required_level = offer.required_level
  		max_required = required_level if Level.compare(max_required, required_level)
  		max_provided = provided_level if Level.compare(max_provided, provided_level)
  	end
  	not Level.compare(max_provided, max_required)
  end

  private

  	def check user
  		reset_errors
	  	set_error "Invalid user" if user.nil?
	  	set_error "This item is out of stock" unless stock_validation
	  	set_error "Item not available for #{user.public_gender.pluralize}" unless gender_validation user.gender
	  	set_error "Needs to be older than #{self.min_age} years old" unless min_age_validation user.age
	  	set_error "Needs to be younger than #{self.max_age} years old" unless max_age_validation user.age
	  	set_error "This item is not yet available" unless buyable_from_validation
	  	set_error "This item is no longer available" unless buyable_until_validation
	  	self.offers.each do |offer|
	  		errors = offer.buyable user 
	  		errors.each do |error|
	  			set_error error 
	  		end
	  	end
  	end

  	def check! user
	  	set_exception "Invalid user" if user.nil?
	  	set_exception "This item is out of stock" unless stock_validation
	  	set_exception "Item not available for #{user.public_gender.pluralize}" unless gender_validation user.gender
	  	set_exception "Needs to be older than #{self.min_age} years old" unless min_age_validation user.age
	  	set_exception "Needs to be younger than #{self.max_age} years old" unless max_age_validation user.age
	  	set_exception "This item is not yet available" unless buyable_from_validation
	  	set_exception "This item is no longer available" unless buyable_until_validation
  	end

	  def set_error msg
	  	unless msg.empty?
	  		@errors << msg
	  	end
	  end

	  def set_exception msg
			raise Exceptions::ComboRestrictionsException.new(message: msg)
	  end

	  def reset_errors
	  	@errors = Array.new()
	  end

	  def stock_validation
	  	self.stock > 0
	  end

	  def gender_validation gender
	  	self.gender == 0 or self.gender == gender
	  end

	  def min_age_validation age
	  	self.min_age <= age
	  end

	  def max_age_validation age
	  	self.max_age >= age
	  end

	  def buyable_from_validation
	  	self.buyable_from <= DateTime.now
	  end

	  def buyable_until_validation
	  	self.buyable_until >= DateTime.now
	  end

end

lets/app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :logged_in_account, only: [:show, :new, :create, :update, :destroy]
  before_action :account_is_owner, only: [:new, :create, :update, :destroy]

  def show
  	@combo = Combo.find(params[:id])
  	@offer = Offer.new()
  end

  def new
  	@event = Event.find(params[:event_id])
  	@combo = Combo.new()
  end

	def create
  	@event = Event.find(params[:event_id])
  	@combo = @event.combos.create(combo_params)
  	if @event.save
      flash[:success] = "New combo created!"
      redirect_to @event
  	else
  		flash[:danger] = "Couldn't create the combo"
  		render 'new'
  	end
	end

	def update
  	@combo = Combo.find(params[:id])
  	@event = @combo.event
  	if @combo.update_attributes(combo_params)
      flash[:success] = "Combo updated!"
      redirect_to @event
  	else
  		flash[:danger] = "Couldn't update the combo"
  		render 'events/show'
  	end
	end

	def destroy
		@combo = Combo.find(params[:id])
		@event = @combo.event
		@combo.destroy
		flash[:success] = "Combo removed"
		redirect_to @event
	end

	private
		
		def combo_params
			params.require(:combo).permit(
				:name,
		    :description,
		    :buyable_from,
		    :buyable_until,
		    :min_age,
		    :max_age,
		    :gender,
		    :stock)
		end

		def account_is_owner
			if (event_id = params[:event_id]).nil?
				combo = Combo.find(params[:id])
				event = combo.event unless combo.nil?
			else
				event = Event.find(event_id)
			end

			if event.nil?
				flash[:danger] = 'Invalid data'
				redirect_to root_url
			else
				account_is_owner? event.producer
			end
		end

end

lets/app/helpers/combos_helper.rb
module CombosHelper
end

lets/app/views/combos/_combo.html.erb
<li class= "card">
	<h5><%= link_to combo.name, combo_path(combo.id) %>: <%= combo.price %></h5>
	<p><%= combo.description %></p>
	<ul>
		<%= render combo.offers %>
	</ul>
</li>

lets/app/views/combos/new.html.erb
<% provide :title, "New Combo"%>
<h3><%= @event.name %>'s new combo</h3>
<%= form_for [@event, @combo] do |f| %>
 	<% @object_with_errors = @combo %>
	<%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.label :min_age %>
  <%= f.number_field :min_age, class: 'form-control' %>

  <%= f.label :max_age %>
  <%= f.number_field :max_age, class: 'form-control' %>

  <%= f.label :gender %>
  <%= f.number_field :gender, class: 'form-control' %>

  <%= f.label :stock %>
  <%= f.number_field :stock, class: 'form-control' %>

  <%= f.label :buyable_from %>
  <%= f.date_select :buyable_from, class: 'form-control' %>

  <%= f.label :buyable_until %>
  <%= f.date_select :buyable_until, class: 'form-control' %>

  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

lets/app/views/combos/show.html.erb
<% provide(:title, @combo.name) %>
<h3><%= @combo.name %></h3>
<h4><%= link_to @combo.event.name, @combo.event %></h4>
<div class = "card">
<p><%= @combo.description %></p>
<p>Available from 
	<%= @combo.buyable_from.strftime("%m/%d/%y %I:%M%p") %> to 
	<%= @combo.buyable_until.strftime("%m/%d/%y %I:%M%p") %>
</p>
<p>
	<%= link_to "$#{@combo.price}", combo_purchases_path(@combo), method: :post,
                                data: { confirm: "You sure?" }, class: 'btn btn-primary'  %>
</p>
</div>
<h4>Offers:</h4>
<ul>
	<%= render @combo.offers %>
</ul>

<div class="row">
  <div class="col-md-6">
		<% if logged_in? and is_owner? @combo.event.producer %>
			<%= form_for [@combo, @offer] do |f| %>

			 	<% @object_with_errors = @offer %>
				<%= render 'shared/error_messages' %>

			  <%= f.label :price %>
			  <%= f.number_field :price, class: 'form-control' %>

			  <%= f.label :redeem_start %>
			  <%= f.datetime_select :redeem_start, class: 'form-control input-short' %>

			  <%= f.label :redeem_finish %>
			  <%= f.datetime_select :redeem_finish, class: 'form-control' %>

				<%= f.label :product_id %><br />
		  	<%= f.select :product_id, options_for_select(Product.all.map{|s|[s.name, s.id]}), class: 'form-control' %>

			  <%= f.submit "Add", class: "btn btn-primary" %>
			<% end %>
		<% end %>
	</div>
  <div class="col-md-6">

		<% unless @errors.nil? %>
			<p>Can't buy this combo:</p>
			<ul>
				<% @errors.each do |error| %>
					<li><%= error %></li>
				<% end %>
			</ul>
		<% end %>
	</div>
</div>