lets/config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :users do 
    member do
      post   '/admin',   to: 'admins#create'
      delete '/admin',   to: 'admins#destroy'
    end
    resources :purchases, only: [:index]
    resources :events, only: [:index]
  end
  resources :producers do
    resources :prod_owners, only: [:create] 
    resources :events, only: [:index, :new, :create]
  end
  resources :prod_owners, only: [:update, :destroy]
  resources :events, only: [:update, :destroy, :show, :index, :edit] do
    resources :combos, only: [:new, :create]
  end
  resources :combos, only: [:show, :update, :destroy] do
    resources :offers, only: [:create]
    resources :purchases, only: [:create]
  end
  resources :offers, only: [:update, :destroy]
  resources :purchases, only: [:destroy, :show]
  resources :products

	root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

lets/app/models/event.rb
class Event < ApplicationRecord

	belongs_to :producer
  has_many :combos, dependent: :destroy
  has_many :admissions, dependent: :destroy
  has_many :users, through: :admissions

	validates :name,				presence: true, length:{maximum: 50, minimum: 5}
	validates :description,	presence: true, length:{maximum: 250, minimum: 10}
  validates :capacity, 		presence: true, :inclusion => 20..5000, numericality: { only_integer: true }
  validates :min_age, 		presence: true, :inclusion => 14..75, numericality: { only_integer: true }
  validates :max_age, 		presence: true, :inclusion => 18..100, numericality: { only_integer: true }
  validates :open_date,		presence: true
  validates :close_date,	presence: true
  validates :id,					uniqueness: {scope: :producer_id, message: "Event alreday belongs to producer"}

	validates_format_of :name, with: /\A[A-Za-z0-9]+(((\ \&|\.|\!{1,4})\ |[\ \-\_@\.\&]|\ \(|\()?[A-Za-z0-9]+\)?)*(\!{1,4}|\.?)\z/i
	
end

lets/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_account, only: [:new, :create, :edit, :update, :destroy]
  before_action :is_admin_or_owner, only: [:destroy]
  before_action :account_is_owner, only: [:new, :create, :edit, :update, :destroy]

  def new
  	@producer = Producer.find(params[:producer_id])
  	@event = Event.new()
  end

  def show
  	@event = Event.find(params[:id])
  end

  def edit
  	@event = Event.find(params[:id])
  end

  def index
  	if params[:producer_id]
      index_producer
      return
    end
    if params[:user_id]
      index_user
      return
    end
    index_regular
  end

  def create
  	@producer = Producer.find(params[:producer_id])
  	@event = @producer.events.create(event_params)
  	if @producer.save
      flash[:success] = "New event created!"
      redirect_to @event
  	else
  		render 'new'
  	end
  end

  def update
		@event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated!"
      redirect_to @event
    else
      redirect_to root_url
    end
  end

  def destroy
		event = Event.find(params[:id])
    producer = event.producer
    if event.destroy
	    flash[:success] = "Event successfuly removed"
	    redirect_to producer_events_url producer
	  else
	  	flash[:danger] = "Event can't be removed now"
	  	redirect_to root_url
	  end
  end

  private

  	def event_params
			params.require(:event).permit(:name, :description, :capacity, :min_age, :max_age, :open_date, :close_date)
		end

		def is_admin_or_owner
			unless current_account.admin?
	      account_is_owner
	    end
  	end

  	def account_is_owner
      if params[:producer_id].nil?
        event = Event.find(params[:id])
        producer = event.producer
      else
        producer = Producer.find(params[:producer_id])
      end
  		account_is_owner? producer
  	end

    def index_producer
      @producer = Producer.find(params[:producer_id])
      @events = @producer.events
      render 'events/index_producer'
    end

    def index_user
      @user = User.find(params[:user_id])
      @events = @user.events
      render 'events/index_user'
    end

    def index_regular
      @events = Event.paginate(page: params[:page])
    end
end

lets/app/helpers/events_helper.rb
module EventsHelper
end

lets/app/views/events/_event.html.erb
<li class="card">
  <h5><%= link_to "#{event.name}: ", event %><h5>
  <span><%= event.description %></span>
  <p>
  	capacity: <%= event.capacity %> |
  	min age: <%= event.min_age %> |
  	max age: <%= event.max_age %> |
  	opens: <%= event.open_date.strftime("%m/%d/%y") %> |
  	closes: <%= event.close_date.strftime("%m/%d/%y") %>
  </p>

  <% if is_owner?(event.producer) %>
    <%= link_to "Edit", edit_event_path(event) %> | 
    <%= link_to "Delete", event, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

lets/app/views/events/edit.html.erb
<% provide :title, "Edit Event"%>
<h3>Edit Event</h3>
<%= form_for @event do |f| %>
 	<% @object_with_errors = @event %>
	<%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity, class: 'form-control' %>

  <%= f.label :min_age %>
  <%= f.number_field :min_age, class: 'form-control' %>

  <%= f.label :max_age %>
  <%= f.number_field :max_age, class: 'form-control' %>

  <%= f.label :open_date %>
  <%= f.date_select :open_date, class: 'form-control' %>

  <%= f.label :close_date %>
  <%= f.date_select :close_date, class: 'form-control' %>

  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

lets/app/views/events/index.html.erb
<% provide(:title, 'Events') %>
<h3>Events</h3>

<ul>
  <%= render @events %>
</ul>

lets/app/views/events/index_producer.html.erb
<% provide(:title, "#{@producer.fantasy_name}'s events") %>
<h3><%= @producer.fantasy_name %>'s events</h3>

<ul>
  <%= render @events %>
</ul>

<% if logged_in? and is_owner? @producer %>
	<%= link_to "New Event", new_producer_event_path(@producer), class: 'btn btn-primary' %>
<% end %>

lets/app/views/events/index_user.html.erb
<% provide(:title, "#{@user.first_name}'s events") %>
<h3><%= @user.first_name %>'s events</h3>

<ul>
  <%= render @events %>
</ul>

lets/app/views/events/new.html.erb
<% provide :title, "New Event"%>
<h3>New Event</h3>
<%= form_for [@producer, @event] do |f| %>
 	<% @object_with_errors = @event %>
	<%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity, class: 'form-control' %>

  <%= f.label :min_age %>
  <%= f.number_field :min_age, class: 'form-control' %>

  <%= f.label :max_age %>
  <%= f.number_field :max_age, class: 'form-control' %>

  <%= f.label :open_date %>
  <%= f.datetime_select :open_date, class: 'form-control' %>

  <%= f.label :close_date %>
  <%= f.datetime_select :close_date, class: 'form-control' %>

  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

lets/app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<h3><%= @event.name %></h3>
<h4><%= link_to @event.producer.fantasy_name, @event.producer %></h4>
<p class="card"><%= @event.description %>
	capacity: <%= @event.capacity %> |
	ages: <%= @event.min_age %> to
	<%= @event.max_age %> |
	opens: <%= @event.open_date.strftime("%m/%d/%y %I:%M%p") %> |
	closes: <%= @event.close_date.strftime("%m/%d/%y %I:%M%p") %>
</p>

<h4>Combos</h4>
<ul>
	<%= render @event.combos %>
</ul>

<% if is_owner?(@event.producer) %>
	<p><%= link_to "New Combo", new_event_combo_path(@event), class: 'btn btn-primary' %></p>
  <%= link_to "Edit", edit_event_path(@event) %> | 
  <%= link_to "Delete", @event, method: :delete,
                                data: { confirm: "You sure?" } %>
<% end %>