lets/config/routes.rb
Rails.application.routes.draw do

  resources :accounts
  resources :users do 
    member do
      post   '/admin',   to: 'admins#create'
      delete '/admin',   to: 'admins#destroy'
    end
    resources :purchases, only: [:index]
    resources :events, only: [:index]
  end
  resources :producers do
    resources :prod_owners, only: [:create] 
    resources :events, only: [:index, :new, :create]
  end
  resources :prod_owners, only: [:update, :destroy]
  resources :events, only: [:update, :destroy, :show, :index, :edit] do
    resources :combos, only: [:new, :create]
  end
  resources :combos, only: [:show, :update, :destroy] do
    resources :offers, only: [:create]
    resources :purchases, only: [:create]
  end
  resources :offers, only: [:update, :destroy]
  resources :purchases, only: [:destroy, :show]
  resources :products

	root 'static_pages#landing'
  get '/about', to: 'static_pages#about'

  get '/signup',  to: 'accounts#new'
  post '/signup',  to: 'accounts#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

end

lets/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Let's Web App</a>
    produced and manteinded by LET'S SpA
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

lets/app/views/layouts/_header.html.erb
<header class="orange navbar navbar-fixed-top navbar-inverse ">
  <div class="container">
  <img src="http://fileserver.imagebucket.net/i/00000/ide5zfk5laee_t.jpg" id="logo-img">

    <%= link_to "LET'S", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Events", user_events_path(current_user) %></li>
              <li><%= link_to "My Purchases", user_purchases_path(current_user) %></li>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

lets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%=full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<%= render 'layouts/header' %>
	<body>
    <div class = 'container'>
			<% flash.each do |message_type, message| %>
	      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	    <% end %>
			<%= yield %>
      <%= render 'layouts/footer' %>
    </div>

		<%= debug(params) if Rails.env.development? %>
	</body>
</html>